### ISSUE TITLE
`toxcore_tests::network_tests` fail

### ISSUE THREAD

**Issue by kpp** [zetok/tox#86]
```
---- toxcore_tests::network_tests::networking_core_new_test stdout ----
	thread 'toxcore_tests::network_tests::networking_core_new_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4

---- toxcore_tests::network_tests::networking_core_register_test stdout ----
	thread 'toxcore_tests::network_tests::networking_core_register_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
```

```
test toxcore_tests::network_tests::networking_core_new_test ... FAILED
test toxcore_tests::network_tests::networking_core_register_test ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4


thread 'thread '<unnamed><unnamed>' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', ', /checkout/src/libcore/result.rs:860:4/checkout/src/libcore/result.rs:thread '860
:4
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', 4/checkout/src/libcore/result.rs
:860:4<unnamed>
' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4
thread 'thread 'thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:860:4

```

**Comment by zetok** [comment]
I think that the following things can be removed from `network.rs`:

- `PacketHandlerCallback`
- `PacketHandles`
- `NetworkingCore`

None of them are actually used, and given the framework provided by tokio it doesn't seem likely for those to be of use in the future.

This probably would address the problem with open files.
